#version 450

layout (local_size_x = 256) in;

// Binding data buffers (like NumPy arrays)
layout(std430, binding = 0) buffer BufferA { float a[]; };
layout(std430, binding = 1) buffer BufferB { float b[]; };
layout(std430, binding = 2) buffer BufferOut { float result[]; };

void main() {
    uint gID = gl_GlobalInvocationID.x;
    
    // Equivalent to: result[i] = a[i] + b[i]
    result[gID] = a[gID] + b[gID];
}